name: evidence_deploy

on:
  workflow_run:
    workflows: ["dbt_stg_ci"]
    types:
      - completed
  workflow_dispatch:  # allows manual triggering too

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reports

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Create GCP credentials file
        run: echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > gcp-key.json

      - name: Build Evidence site
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/reports/gcp-key.json
        run: |
          npm run sources
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: './reports/build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}